django_project/blog/urls.py
from django.urls import path, include
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeletelView,
    CommentCreateView,
    comment_delete,
)





urlpatterns = [
    #######################
    #
    # routing using function based view
    #
    ######################

    # path('', views.home , name='blog-home'),

    ######################
    #
    # routing using class based views
    #
    ########################

    # add .as_view() when referencing to class based view
    path('', PostListView.as_view(), name='blog-home'),

    # route to a specific post using primary key or pk and what kind of variable it is <int:pk>
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),

    # to be able to use this route, create a template
    # using this format <model name>_form.html
    # ex. post_form.html
    path('post/new/', PostCreateView.as_view(), name='post-create'),

    # just pass in the primary key of the post and all will be handled by the view method
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),

    path('post/<int:pk>/delete/', PostDeletelView.as_view(), name='post-delete'),

    path('comment/<int:pk>/new/', CommentCreateView.as_view(), name='comment-create'),


    path('comment/<int:pk>/delete', comment_delete, name='comment-delete'),


]

django_project/django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password/', user_views.change_password, name='change_password'),
    path('', include('blog.urls')),
]

# #  if in debug mode add static files on urlpatters
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import redirect
from rest_framework import serializers



class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # create a get absolute url method
    # so that django_activity will know how to find the location of a specific post
    # use reverse to use the full url to that route as a string


    def get_absolute_url(self):
        # return a path to a specific post
        # reverse(<url destination, kwargs={<url parameter>: <instance of a specific post>}>
        return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    message = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    # use ForeignKey to use one to many relationship in django_activity
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.message

    def serialize(model, many=False):
        if many:
            return map(Comment.serializer, model)
        return Comment.serializer(model)

    def serializer(model):
        dict_model = model_to_dict(model)
        return dict_model

    def get_absolute_url(self):
        # return a path to a specific post
        # reverse(<url destination, kwargs={<url parameter>: <instance of a specific post>}>
        return reverse('blog-home')

#--------------------------------------------------------------------------
# class OtherParty(models.Model):
#     accident = models.ForeignKey(Accident)
#     other_party_name = models.CharField(max_length=100)
#     other_party_drivers_license_num = models.CharField(max_length=100)
#     other_party_license_plate_num = models.CharField(max_length=100)
#     other_party_contact_num = models.CharField(max_length=100)
#     other_party_damage_loc = models.TextField()
#     other_party_damage_comments = models.TextField()
#     other_party_date_added = models.DateField(auto_now_add=True, null=True)
#
#     def __unicode__(self):
#         return "%s - %s" % (self.id,self.other_party_name)
#
#     @staticmethod
#     def serialize(model, many=False):
#         if many:
#             return map(OtherParty.serializer, model)
#         return OtherParty.serializer(model)
#
#     @staticmethod
#     def serializer(model):
#         dict_model = model_to_dict(model)
#         return dict_model

django_project/blog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


from django.http import HttpResponse

from django.db import models

#############################
#
#   function based views
#
#############################

#
# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'blog/home.html', context)

##############################
#
#   class based views
#
#############################


class PostListView(ListView):
    model = Post  # what model to query

    # this is the default TEMPLATE NAME format when using views
    # <app name>/<model>_<view type>.html
    # example: blog/post_list.html
    # when not using the default TEMPLATE NAME format
    # use below format to reference predefined template
    template_name = 'blog/home.html'

    context_object_name = 'posts'  #
    # #  context_object_name is the same as below example
    # context = {
    #         'posts': Post.objects.all()
    #     }
    #     return render(request, 'blog/home.html', context)

    # order of query by date from latest post


    # query a foreign
    # def get_queryset(self):
    #     queryset = (Comment.objects
    #                 .all()
    #                 .prefetch_related('message')
    #                 .order_by('-date_posted'))
    #     return queryset

    ordering = ['-date_posted']


class PostDetailView(DetailView):
    # all we need is to specify that Model
    # and the functions are automatically generated
    model = Post


# LoginRequiredMixin argument is an alternative for login decorator for function based views
# it means adding a functionality to a view telling that a
# user can never add a post when not logged in
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post

    # this is the field that would be populated in the model
    # and will automatically generated in the template
    fields = ['title', 'content']

    # in the model we have an AUTHOR field and it cannot be null
    # so we need to override form_valid method to update the author to be the current logged in user
    def form_valid(self, form):  # form valid takes a self, and form as an argument

        # before its submitted take that instance and
        # set the author to be the logged in user
        form.instance.author = self.request.user

        # validated the form and pass the form as an argument
        return super().form_valid(form)

    # it will create the post successfully but it will create an error
    # because it didn't know where to redirect when submitted.
    # we need to redirect to a certain url once the post is created
    # steps:
    # create a get absolute url method to path of specific instance
    # go to Post model to create a specific url


# UserPassesTestMixin is a test for users.
# this only means that if the author of the post is not the current logged in user
# it cannot update that post
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # from UserPassesTestMixin
    # test a user
    def test_func(self):
        # get the exact post that will be updated by using .get_object()
        post = self.get_object()

        # check if the author is currently the logged in user
        if self.request.user == post.author:

            # return true if the author is currently
            # the logged in user and allow the user to update the post
            return True

        # else return false if its not and it will never be updated
        # and will return an error
        return False


class PostDeletelView(LoginRequiredMixin, UserPassesTestMixin, DeleteView): # all mixins will be to the left of the views inheritance
    model = Post

    # add success_url to redirect when its deleted
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class CommentCreateView(LoginRequiredMixin, CreateView):

    model = Comment
    fields = ['message']

    def form_valid(self, form):

        # return HttpResponse("1")
        # user_data = request.data

        form.instance.author = self.request.user

        form.instance.post = Post.objects.get(pk=self.kwargs['pk'])

        # return HttpResponse(self.kwargs['pk'])
        #
        # form.instance.post =  # get the value of pk in url
        # r = self.kwargs['pk']
        # comments = Comment.object.filter(id=pk)
        # comments.message = user_data['message']
        # comments.save()
        # list rotue
        # detail route

        return super().form_valid(form)
        # return r

@login_required
def comment_delete(request, pk):

    comment = Comment.objects.get(id=pk)
    comment.delete()

    return render(request, 'blog/home.html', {'message': 'comment deleted'})
    # return HttpResponse(comment)

django_project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>My site - {{ title }}</title>
    {% else %}
        <title>My site</title>
    {% endif %}
</head>
<body>
    <h1>My site</h1>
    {% if user.is_authenticated %}
        <p>Welcome, <strong>{{ user.username }}</strong></p>
    {% endif %}
    <a href="{% url 'blog-home' %}">Home</a> |
    {% if user.is_authenticated %}

        <a href="{% url 'post-create' %}">New Post</a> |
        <a href="{% url 'profile' %}">Profile</a> |
        <a href="{% url 'logout' %}">Logout</a> |

    {% else %}
        <a href="{% url 'login' %}">Login</a> |
        <a href="{% url 'register' %}">Register</a>
    {% endif %}
    <hr>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

django_project/blog/templates/blog/comment_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        <h2>Delete Post</h2>
        {% csrf_token %}

        <h3>Are you sure you want to delete the comment?</h3>


        <button type="submit">Delete</button>
        <button><a href="{% url 'post-detail' object.id %}">Cancel</a></button>
    </form>

{% endblock %}

django_project/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Comment</button>
    </form>

{% endblock %}

django_project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    {% for post in posts %}
        <!--passing an id using /url '<destination>' <id of individual post   >/-->
        <!--in the url it will look like this -->
        <!--example: blog/2-->

        <fieldset>
            <a href="{% url 'post-detail' post.id %}"><h1>{{ post.title }} </h1></a>
            <p>By {{ post.author }} on {{ post.date_posted | date:"F d Y" }}</p>

            <p>{{ post.content }}</p>

            {% if user.is_authenticated %}
                <button><a href="{% url 'comment-create' post.id %}">add comment</a></button>
            {% endif %}

            <h2>comments</h2>
            <hr>
                {% for comment in post.comment_set.all %}
                    <h5>{{ comment.author }} </h5>
                    <p>{{ comment.message }}</p>
                    <h5>{{ comment.date_posted }}</h5>

                {% if user.is_authenticated %}
                    {% if comment.author == user %}
                        <button><a href="{% url 'comment-delete' comment.id %}">Delete Comment</a>t</button>
                    {% endif %}

                {% endif %}
            <hr>
                {% endfor %}
        </fieldset>


    {% endfor %}
    <br>
    <br>
    <br>


{% endblock %}

django_project/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        <h2>Delete Post</h2>
        {% csrf_token %}

        <h3>Are you sure you want to delete the comment"</h3>

        {{ form.as_p }}

        <button type="submit">Delete</button>
        <button><a href="{% url 'blog-home' object.id %}">Cancel</a></button>
    </form>

{% endblock %}

django_project/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

    <!--when dealing with detail_views it expects the context of this template to be called object-->

    <h1>{{ object.title }}</h1>
    <p>By {{ object.author }} on {{ object.date_posted | date:"F d Y" }}</p>
    <p>{{ object.content }}</p>
    {% if object.author == user %}
        <button><a href="{% url 'post-update' object.id %}">update</a></button>
        <button><a href="{% url 'post-delete' object.id %}">delete</a></button>

        <h1>comment</h1>
        {% for comment in object.comment_set.all %}
            {{ comment.message }}
        {% endfor %}
    {% endif%}
    <br>



{% endblock %}

django_project/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Post</button>
    </form>

{% endblock %}